# Configuration for building a custom golangci-lint binary with the log-linter plugin.
# See https://golangci-lint.run/plugins/module-plugins/

version: v1.64.4 
plugins:
  # Load plugin from local source
  - module: 'github.com/AlexanderGhosty/log-linter'
    import: 'github.com/AlexanderGhosty/log-linter/plugin'
    path: .

